logging:
  file: logs/cloud-web.log
  level:
    root: info
    com.dsjk.platform: debug

server:
  port: 8080

spring:
  application:
    name: cloud-web
  aop:
    proxy-target-class: true

# dubbo
dubbo:
  application-name: web
  annotation-package: com.dsjk.boot.web.user
  protocol-name: dubbo
  protocol-port: 20882
  registry-protocol: zookeeper
  registry-address: zookeeper://127.0.0.1:2181


