# log
logging:
    file: logs/boot-service-user.log
    level:
        root: info
        com.dsjk.boot.service.user: debug

druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backend-boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    #DataSource Global Setting
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

# MyBatis
mybatis:
  type-aliases-package: com.dsjk.boot.common.bean
  configuration:
    map-underscore-to-camel-case: true

mapper:
    mappers:
        - com.dsjk.boot.common.base.CommonMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# dubbo
dubbo:
    application-name: service-user
    annotation-package: com.dsjk.boot.service.user.service
    protocol-name: dubbo
    protocol-port: 20881
    registry-protocol: zookeeper
    registry-address: zookeeper://127.0.0.1:2181
